services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: kbee_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-kbee_root_password}
      MYSQL_DATABASE: ${DB_NAME:-kbee_manager}
      MYSQL_USER: ${DB_USER:-kbee_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-kbee_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - kbee_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Flask API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kbee_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://${DB_USER:-kbee_user}:${DB_PASSWORD:-kbee_password}@db:3306/${DB_NAME:-kbee_manager}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - DOMAIN=${DOMAIN:-localhost}
      - PROTOCOL=${PROTOCOL:-http}
      - PORT=${PORT:-80}
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/static:ro
    networks:
      - kbee_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kbee_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8080}:80"
      - "${FRONTEND_SSL_PORT:-8443}:443"
    depends_on:
      - backend
    networks:
      - kbee_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: kbee_redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - kbee_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  kbee_network:
    driver: bridge