services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: kbee_db_local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kbee_root_password
      MYSQL_DATABASE: kbee_manager
      MYSQL_USER: kbee_user
      MYSQL_PASSWORD: kbee_password
    volumes:
      - mysql_data_local:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - kbee_local_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Flask API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kbee_backend_local
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://kbee_user:kbee_password@db:3306/kbee_manager
      - SECRET_KEY=your-secret-key-change-in-production
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DOMAIN=localhost
      - PROTOCOL=http
      - PORT=5000
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/static:ro
      - ./logs/backend:/app/logs
    networks:
      - kbee_local_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
      args:
        VITE_DOMAIN: localhost
        VITE_APP_NAME: "KBee Manager"
        VITE_VERSION: 1.0.0
        VITE_COMPANY_NAME: KBee
        VITE_API_URL: http://localhost:8000/api
    container_name: kbee_frontend_local
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./logs/frontend:/var/log/frontend
    networks:
      - kbee_local_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data_local:
    driver: local

networks:
  kbee_local_network:
    driver: bridge
